spring:
  application:
    server-port: 8080
    name: saude-praja-api
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      #show-sql: true
      #format_sql: true
  datasource:
    url: jdbc:mysql://saudepraja-db.ce7oksw2k2ep.us-east-1.rds.amazonaws.com:3306/saudepraja_db
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
springdoc:
  version: '@springdoc.version@'
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    path: /swagger-ui.html
server:
  max-http-request-header-size: 1000KB
logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # Um dia (1000 * 60 * 60 * 24) em milesegundos

saudepraja:
  auth:
    provider-url: "http://localhost:8080"
  storage:
    s3:
      id-chave-acesso: ${S3_STORAGE_KEY}
      chave-acesso-secreta: ${S3_STORAGE_KEY_PASSWORD}
      bucket: ${S3_STORAGE_BUCKET_NAME}
      regiao: ${S3_STORAGE_REGION}
      diretorio-fotos: ${S3_STORAGE_FOLDER}