spring:
  application:
    name: saude-praja-api
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    #show-sql: true
    #format_sql: true
  datasource:
    #url: jdbc:mysql://host.docker.internal:3306/saudepraja_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${MYSQL_DATABASE:saudepraja_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 30MB
springdoc:
  version: '@springdoc.version@'
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    path: /swagger-ui.html
server:
  port: 8080
  max-http-request-header-size: 1000KB
logging:
  level:
    org:
      springframework:
        security: DEBUG
      org.springframework.boot.actuate: TRACE
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # Um dia (1000 * 60 * 60 * 24) em milesegundos

saudepraja:
  auth:
    provider-url: "http://localhost:8080"
  storage:
    s3:
      id-chave-acesso: ${S3_STORAGE_KEY}
      chave-acesso-secreta: ${S3_STORAGE_KEY_PASSWORD}
      bucket: amzn-s3-saudepraja-bucket
      regiao: us-east-1
      diretorio-fotos: pedidos-exame